<?php

namespace ContainerNbxm9pQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerforhimService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ngASPaK.App\Controller\ProductController::forhim()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ngASPaK.App\\Controller\\ProductController::forhim()'] = ($container->privates['.service_locator.ngASPaK'] ?? $container->load('get_ServiceLocator_NgASPaKService'))->withContext('App\\Controller\\ProductController::forhim()', $container);
    }
}
