<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNbxm9pQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNbxm9pQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNbxm9pQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNbxm9pQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNbxm9pQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nbxm9pQ',
    'container.build_id' => 'b913c6f3',
    'container.build_time' => 1748561612,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNbxm9pQ');
