<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdu28Jb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdu28Jb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZdu28Jb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZdu28Jb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZdu28Jb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zdu28Jb',
    'container.build_id' => 'b1f56225',
    'container.build_time' => 1748551216,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdu28Jb');
